### ISSUE TITLE
Run terminal commands

### ISSUE THREAD

**Issue by Angelk90** [okwasniewski/react-native-menubar-extra#13]
Hi @okwasniewski, It would be useful to be able to execute terminal-type commands, like this one here:

```js
const { exec } = require("child_process");

...
          exec("ls -la", (error, stdout, stderr) => {
            if (error) {
                console.log(`error: ${error.message}`);
                return;
            }
            if (stderr) {
                console.log(`stderr: ${stderr}`);
                return;
            }
            console.log(`stdout: ${stdout}`);
        });
```

So I thought it would be useful to adopt a server solution like this: https://testableapple.com/gaining-access-to-command-line-from-maestro/

**Comment by okwasniewski** [comment]
Hey, so according to [this](https://stackoverflow.com/questions/66265992/execute-a-shell-command-from-react-native-app-for-mac-os) stackoverflow thread you can use [this](https://www.npmjs.com/package/react-native-childprocess) library to achive it in React Native. However this is way out of scope for `react-native-menubar-extra` library, therefore I'm closing this issue.

**Comment by okwasniewski** [comment]
It works for me did you ran `pod install` after installing this library?

**Comment by okwasniewski** [comment]
You need to clean up the old build. Inside `macos` folder run `rm -rf Pods build` and then install pods again (`pod install`)

**Comment by Saadnajmi** [comment]
See my explanation here: https://github.com/microsoft/react-native-macos/issues/1937#issuecomment-1743062559

It's not currently possible to run arbitrary node native modules with React Native macOS, as they have two completely separate methods of JS->Native (C++) communication.

**Comment by okwasniewski** [comment]
@Saadnajmi The solution for this particular issue would be to create an RN Macos library that would wrap another native library to execute shell commands like https://github.com/JohnSundell/ShellOut right?

**Comment by Saadnajmi** [comment]
> @Saadnajmi The solution for this particular issue would be to create an RN Macos library that would wrap another native library to execute shell commands like https://github.com/JohnSundell/ShellOut right? 

Yep, unless the other project I mentioned lands and we can get all node native modules to "just work" with react native macOS (while using Hermes). But you know, that's a ways away I think, and writing your own native module OS the way to go IMO
