### ISSUE TITLE
Project fails to build after adding the package

### ISSUE THREAD

**Issue by x-ji** [okwasniewski/react-native-menubar-extra#16]
This is exactly what I've been needing and thanks so much for creating it 🙌 . I tried it out on a vanilla React Native app (generated via `npx react-native@latest init Test --template "react-native@^0.71.0"` then `npx react-native-macos-init`). After running `npm install react-native-menubar-extra` and `cd macos && pod install` and I try to run `npx react-native run-macos`, the project build failed however. (I was able to successfully launch the vanilla app. My cocoapods is installed via asdf-managed Ruby.) I'm not familiar with XCode so I'm not sure what would be the best way to look for relevant logs. I see from the command line:

```
In file included from /Users/jx/Projects/Frontend/Test/macos/build/generated/ios/FBReactNativeSpecJSI-generated.cpp:10:
In file included from /Users/jx/Projects/Frontend/Test/macos/build/generated/ios/FBReactNativeSpecJSI.h:13:
In file included from /Users/jx/Projects/Frontend/Test/macos/Pods/Headers/Public/ReactCommon/react/bridging/Bridging.h:17:
/Users/jx/Projects/Frontend/Test/macos/Pods/Headers/Public/ReactCommon/react/bridging/Object.h:13:10: fatal error: 'butter/map.h' file not found
#include <butter/map.h>
         ^~~~~~~~~~~~~~
1 error generated.
```

If I try to run `Build` from XCode itself, I get a "Command PhaseScriptExecution failed with a nonzero exit code" on RNCore.

Weirdly, I was able to run the example app after cloning the repo without any issue. I also tried to use the exact same react-native version as in the example app to no avail.

I suspect it might have [something to do with cocoapods and the Ruby version on my system](https://stackoverflow.com/questions/53289524/xcode-10-2-1-command-phasescriptexecution-failed-with-a-nonzero-exit-code) (I currently have a global Ruby version set via asdf) but I'm lost. I wonder if there's any pointer to help me debug it. Thanks a lot!

**Comment by Saadnajmi** [comment]
FWIW, you can probably also comment out that header import to `butter/map` locally

**Comment by x-ji** [comment]
Seems that it's an issued caused by CocoaPods caching (maybe due to different `ruby`s present on the system but no idea). I was wondering why `pod install` finished so fast... Doing `rm -rf Pods && rm -rf Podfile.lock && rm -rf build && pod cache clean --all && pod install` as mentioned in https://github.com/facebook/react-native/issues/38520 worked. (Only running `pod deintegrate` and `pod install` wasn't enough.)
