### ISSUE TITLE
Featured request: add title props for MenuBarExtraView

### ISSUE THREAD

**Issue by Ppang0405** [okwasniewski/react-native-menubar-extra#9]
Hi,
I need a title prop in MenuBarExtraView to archive that UI
![image](https://github.com/okwasniewski/react-native-menubar-extra/assets/33455900/c5addf7d-18e3-492d-ae33-cf057491845a)

And a question: do you plan to support SVG icons instead of only SF Symbols?

**Comment by okwasniewski** [comment]
Hey! 

Support for setting title in MenuBarExtraView is added here: #10 - going to release next version soon.

Regarding custom icons: I'm definitely planning to add support for it in upcoming releases.
